### ISSUE TITLE
Django3, bootstrap4, no popup is being shown

### ISSUE THREAD

**Issue by djk2** [djk2/django-popup-view-field#16]
I downloaded the new repo and installed the latest version of jango-popup-view-field. I tried running your demo, but I the popup for the the bootstrap is not displaying. In the logs, it shows that there is a request, but no popup is being shown. Also, I am running Django 3.x.x because I cannot install Django 2.2.9 that is in the requirement.txt.

_Originally posted by @ImanoWilliams in https://github.com/djk2/django-popup-view-field/issues/8#issuecomment-578543913_

**Comment by djk2** [comment]
Thank for yours tests.
You have right, some bug appeared in javascript for bootstrap4. 
Probably I didn't detect it, because my web browser cached old settings. 
I fixed problem and now everything should be fine. 
Let me know if you will be have any problems. 
I also checked compatibility with Django 3.0
Fixes are in  version 0.6.1

**Comment by ImanoWilliams** [comment]
Hi.
I have downloaded the new repo (0.6.1) and tested it.  The popup field view is now being displayed when I use bootstrap 4 for my Django app too. I have not tried to save any data for a form with the popup field. I will let you know if there is any other issue. Right now, it is working great.
Thank you again.

**Comment by djk2** [comment]
Solved
