### ISSUE TITLE
Multiple nested popups

### ISSUE THREAD

**Issue by n3storm** [djk2/django-popup-view-field#3]
Sorry for my laziness but I have been checking lots of libraries looking for nested popups with no luck.

The question is if it handles multiple nested or level popups. For example:

We are at Blog post view: popup select Category (popup 1.0) > Category does not exist > New popup Create category (popup 1.1) > Category form, image for category does not exist > New popup Upload image for category (popup 1.2).

Thanks in advance.

**Comment by djk2** [comment]
Sorry, I never considered that functionality. Probably multiple nested popups can't be created using my library.
