### ISSUE TITLE
AttributeError: 'PopupViewField' object has no attribute 'is_hidden'

### ISSUE THREAD

**Issue by ImanoWilliams** [djk2/django-popup-view-field#4]
I am trying to modify your demo to work with model forms. Below is what I have tried but getting "AttributeError: 'PopupViewField' object has no attribute 'is_hidden'"
<pre> 
class DemoForm(ModelForm):
	class Meta:
		model=Country
		fields ='__all__'
		widget={
		'name':PopupViewField(
                # Attrs for popup
                view_class=SexPopupView,
                popup_dialog_title='What is your SEX',
                # Attr for CharField
                required=True,
                help_text='female or male'
		))}
			

	def __init__(self, *args, **kwargs):
		super(DemoForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
</pre>

**Comment by djk2** [comment]
Can you write some unit test to show problem?

**Comment by ImanoWilliams** [comment]
Sorry I am not able to write a unit test to reproduce this issue. However, The only thing I did was modified the forms.py in the demo app to the code above. Next, I called "python manage.py runserver". After running the server, I got the attribute error.

**Comment by djk2** [comment]
OK, I understand. 
At the end of August I will have time to take care of it.
I will be grateful for your patience.

**Comment by ImanoWilliams** [comment]
@djk2 I want to detailview popupview like so. When the user clicks on the **selectionReason** where the popupfield is place, I want to pass a primary key from the AttackPatternForm to detail view. I will then call the attackpattern values in the template file. 

My issue is how to pass the value from the form and then use it to query in the detailview of the popupfield. 

forms.py
```
class AttackPatternForm(ModelForm):
    class Meta:
        model=AttackPattern
        fields='__all__'
    selectionReason=PopupViewField(
        view_class=SelectionReasonPopUpView,
        popup_dialog_title="Please select a reason for",
        required=True
        )
    def __init__(self, *args, **kwargs):
        super(AttackPatternForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
```

popups.py
```
class SelectionReasonPopUpViews(DetailView):
    template_name = 'popups/selectionReason.html'
    model = AttackPattern
    #How to get a value from the parent form in the detailview?

```

template: 'popups/selectionReason.html
```
<ul>
    <li data-popup-view-value="Description"> {{attackpattern.description}} </li>
	<li data-popup-view-value="Flow" > {{attackpattern.flow}} </li>
</ul>
```

**Comment by ImanoWilliams** [comment]
In stead of pass a widget dict., I did this:

class DemoForm(ModelForm):
	class Meta:
		model=Country
		fields ='__all__'
	name=PopupViewField(
        # Attrs for popup
        view_class=SexPopupView,
        popup_dialog_title='What is your SEX',
        # Attr for CharField
        required=True,
        help_text='female or male'
		)
	code = PopupViewField(view_class=CountryPopupView)
	#country_code = PopupViewField(view_class=CountryPopupView)		

	def __init__(self, *args, **kwargs):
		super(DemoForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
