### ISSUE TITLE
Not work in IIS

### ISSUE THREAD

**Issue by frankwwjj** [djk2/django-popup-view-field#6]
Hi there,

would really appreciate if you let me know the way to fix it.

i have developed a django app which uses your pop up. it works fine on the development server. however, when i deploy the app using IIS on windows server, it stops working - when i click the magnify glass button, nothing happens.

could you please let me know whether there is anything i need to do in iis to get it work again? many thanks

regards,
Jun Wang

**Comment by djk2** [comment]
1. Can you paste here some logs from web browser (JS console) or errors from django ??
2. Does your www server  properly serve static files? 
3. Did you run collectstatic command? 
4.  Does JS files load properly? (YOUR_IP_ADDRESS/static/django_popup_view_field/js/django_popup_view_field.min.js) or you get Http 404

I never deployed django app on windows server. I always use gunicorn + nginx.

**Comment by frankwwjj** [comment]
Hi there,

many thanks for your note, and please see below my answers:

1. Django does not show any errors. the issue is that when i click the button, no window pops up like it should. when i click the button, nothing happens.
2. yes
3. yes
4. http 404 error. however, the pop up window works on my local development server when running pythong manage.py runserver. also, i have installed your application using pip, and the js file you mentioned is stored in C:\virtualenvs\foo\Lib\site-packages\django_popup_view_field\static\django_popup_view_field\js folder.

it will be really appreciated if you could look into my issue!

regards,
James

**Comment by frankwwjj** [comment]
Many thanks!

after i copied the js file from your application folder to the static folder, it worked!

many thanks for your help!

regards,
James

**Comment by djk2** [comment]
Grate.
